### PR TITLE
Add romanian translation

### PR DESCRIPTION
**Pull request by birkof**
This PR adds romanian translation (language: 'ro')

### CODE REVIEW

**Comment by birkof** [comment]
@adriandmitroca can you take a look here? 👯 #gdprmood

**Comment by adriandmitroca** [comment]
Hey,

I feel you - I'll release it within an hour :)

**Comment by adriandmitroca** [comment]
Thanks for your pull request @birkof, 2.2.0 has just been published to npm.

Sorry for the delay and release issues. I already have plans to make npm releases on Travis when commit gets tagged on the GitHub side so it wouldn't require any manual action.

Have a nice day :)

**Comment by birkof** [comment]
Glad I could help 🎉

**Pull request merged**
